### ISSUE TITLE
RF - Mostrar municipio en formulario de actualización de datos en bautizo

### ISSUE THREAD

**Issue by kfajardop** [axelherreram/iglesia-sansare-wep#14]
### Recuperar el nombre del municipio en el formulario de actualización de datos en la creación de bautizos
![image](https://github.com/user-attachments/assets/659788fd-52b6-4b50-bd59-08433260f74f)

Al momento de visualizar los detalles de un bautizo, no muestra el municipio que ingresó el usuario.

**Comment by carolayestephania03** [comment]
El error ocurre porque los factories crean registros aleatorios y no asocian correctamente los municipios con los departamentos. Como resultado, los municipios obtienen un id de departamento que no corresponde, lo que impide que se muestren correctamente al visualizar un registro. Este problema solo ocurrirá en las pruebas, pero no sucederá en producción.
