### ISSUE TITLE
RF - Agregar comentario de 0 resultados en búsqueda de bautizos 

### ISSUE THREAD

**Issue by kfajardop** [axelherreram/iglesia-sansare-wep#8]
### Resultado de la búsqueda de bautizos
Al momento de buscar un bautizo y no se encuentra información, agregar un comentario indicando dicha información para que el usuario tenga conocimiento de que no existe ese dato.

![image](https://github.com/user-attachments/assets/d66b7a40-eedd-49f4-979c-de7cd2726cd0)

**Comment by axelherreram** [comment]
Listo
Se ha agregado una alerta utilizando SweetAlert para notificar cuando no se encuentran registros.

![image](https://github.com/user-attachments/assets/d6d6eff4-c10b-4ee4-bfdd-13056aa4da3a)

Así mismo un mensaje en la tabla
![image](https://github.com/user-attachments/assets/b8188e64-64f6-4f83-bc0e-bd19617fb0de)
