### ISSUE TITLE
RF - No muestra lista de municipios

### ISSUE THREAD

**Issue by mceron666** [axelherreram/iglesia-sansare-wep#9]
Al buscar por nombre, especificar en base a que nombre se buscará, ya que está el nombre de la persona bautizada y el nombre del sacerdote y puede causar confusión
![image](https://github.com/user-attachments/assets/a1f2bd37-b39a-40e4-937e-b2d6f818ac79)

**Comment by axelherreram** [comment]
Listo
![image](https://github.com/user-attachments/assets/37cb636a-7bcd-4adb-b2e9-21a8b593b0e8)
